version: "3.9"
services:
  crypto-analytics-ui:
    build:
      context: .
      dockerfile: Dockerfile
    image: crypto-analytics-ui:prod
    container_name: crypto-analytics-ui
    ports:
      - "8181:80"
    restart: unless-stopped
